language: java
jdk:
- oraclejdk8

before_script: git clone -b travis `git config --get remote.origin.url` target/travis

script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml'

after_success:
  - mvn clean jacoco:prepare-agent test jacoco:report coveralls:jacoco

branches:
  only:
  - master

env:
  global:
  - secure: kr5y/m2LUwcl6O9HorrRgaLNbjmvNjbTy3yEzyrrZc8IJftwFXCOIjsDGEFHguemdzcDY86gSxc3dYGiNOWu++86YXRQy1Y0mCmGUKfY3+L3N98KHHhlj+hFSaKVgDLO2mGWwc69WWo0mCJ04IzHEWKLMfHMC6efNfVrKsqszgk=
  - secure: mYw09dYIdqfPEoUmVapFwerSje/VT4SZe6DNfT3olabQbNM7Q3oaXmlDORK/HAfteVAtMzcVQtu23ukcxKyduUtFrWwhdo/4l7MaDKlZ6G8L/8ioePWE57tp4QQoGgjL0B0NZ3DyFuBuCGBmhE9EhnU07DZ/Dm24uyV3ChCQtgI=
